### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by arthurgrykhno** [arthurgrykhno/homepage#4]

**Comment by ArtemonTheHuman** [comment]
<h2> — I'm the type of rapper - like, I'm never gonna let myself give up. I don't fake relationships, vibes, or anything with people. I just keep it real, and some people think I have a cold heart for that.
I look at my body as an extension of the music. My body is a canvas, and with my tattoos, I want them to be a direct reflection of my thoughts.</h2>

**Comment by arthurgrykhno** [comment]
Great!
