### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by arthurgrykhno** [arthurgrykhno/homepage#5]

**Comment by ArtemonTheHuman** [comment]
- https://www.instagram.com/lilskies/
- https://www.youtube.com/channel/UCLEyFXOmaIgG6h4_6wqLx7Q
- https://soundcloud.com/lil-skies
- https://twitter.com/lilskies
- https://itunes.apple.com/us/artist/lil-skies/1162362760

**Comment by arthurgrykhno** [comment]
Thanks !!!!
