### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by arthurgrykhno** [arthurgrykhno/homepage#6]

**Comment by ArtemonTheHuman** [comment]
<h2>Life</h2>
<h3>August 04, 1998</h3>
<p>Kimetrius Christopher Foose (born August 4, 1998), known by his stage name Lil Skies, is an American rapper, singer and songwriter from Waynesboro, Pennsylvania currently signed to All We Got Entertainment through Atlantic Records.</p>
<h3>October, 2016</h3>
<p>Opened for Fetty Wap at Shippensburg University and later released his first mixtape, Alone, in January 2017. In July 2017, he released two songs, "Red Roses" featuring Landon Cube and "Off The Goop" featuring Sprite Lee. He would later release other songs that year, including "Rude" and "Signs of Jealousy."</p>
<h3>December 2017</h3>
<p>Foose's repertoire of singles caught the attention of Atlantic Records who partnered with his own label, All We Got. Released his first major label mixtape, Life of a Dark Rose, on January 10, 2018. The album debuted at #23 on the Billboard 200 chart and went on to peak at #10.</p>
<h3>February 2019</h3>
<p>In February 2019, Foose announced he's expecting his first child with his longtime girlfriend. In October 2019, Foose acknowledged the birth of his son in an Instagram post.</p>
<h3>March 01, 2019</h3>
<p>On March 1, 2019, Lil Skies released his album Shelby, while simultaneously debuting the music video for lead single "I".</p>
<h2>Music career</h2>
<h3>Albums</h3>
<h4>Life of a Dark Rose</h4>
<ul>
<li>Released: January 10, 2018</li>
<li>Label: All We Got, Atlantic</li>
<li>Format: CD, digital download</li>
</ul>
<h4>Shelby</h4>
<ul>
<li>Released: March 1, 2019</li>
<li>Label: All We Got, Atlantic</li>
<li>Format: CD, digital download</li>
</ul>
<h3>Singles</h3>
<p>Red Roses, 2017</p> <p>Nowadays, 2017</p> <p>Lust, 2017</p>
<p>Welcome to the Rodeo, 2018</p>
<p>I Know You, 2018</p>
<p>Creeping, 2018</p>
<p>Pop Star, 2018</p>
<p>World Rage, 2018</p>
<p>No rest, 2018</p>
<p>Oops want me dead, 2018</p>
<p>Real ties, 2019</p>
<p>Name in the send, 2019</p>
<p>I, 2019</p>
<p>Going off, 2019</p>
<p>Magic, 2019</p>
<p>More money, more ice, 2019</p>
<p>Havin' my way, 2020</p>
<p>Fidget, 2020</p>

**Comment by arthurgrykhno** [comment]
Yeah! That's it!!
