### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by arthurgrykhno** [arthurgrykhno/homepage#7]

**Comment by ArtemonTheHuman** [comment]
<h2>Skills</h2>
<p>Creating hits, skateboarding, make people happy</p>
<h2>Likes</h2>
<p>Love wearing expensive clothes, fast driving foreign cars, counting money &#128520</p>
<p>In love with Mary Jane &#129392 &#128525</p>
<h2>Dislikes</h2>
<p>When money ends (it doesn't &#128513)</p>

**Comment by arthurgrykhno** [comment]
Great)
