### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by arthurgrykhno** [arthurgrykhno/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ArtemonTheHuman** [comment]
<h2>Life</h2>
<h3>August 04, 1998</h3>
<p>Kimetrius Christopher Foose (born August 4, 1998), known by his stage name Lil Skies, is an American rapper, singer and songwriter from Waynesboro, Pennsylvania currently signed to All We Got Entertainment through Atlantic Records.</p>
<h3>October, 2016</h3>
<p>Opened for Fetty Wap at Shippensburg University and later released his first mixtape, Alone, in January 2017. In July 2017, he released two songs, "Red Roses" featuring Landon Cube and "Off The Goop" featuring Sprite Lee. He would later release other songs that year, including "Rude" and "Signs of Jealousy."</p>
<h3>December 2017</h3>
<p>Foose's repertoire of singles caught the attention of Atlantic Records who partnered with his own label, All We Got. Released his first major label mixtape, Life of a Dark Rose, on January 10, 2018. The album debuted at #23 on the Billboard 200 chart and went on to peak at #10.</p>
<h3>February 2019</h3>
<p>In February 2019, Foose announced he's expecting his first child with his longtime girlfriend. In October 2019, Foose acknowledged the birth of his son in an Instagram post.</p>
<h3>March 01, 2019</h3>
<p>On March 1, 2019, Lil Skies released his album Shelby, while simultaneously debuting the music video for lead single "I".</p>
<h2>Music career</h2>
<h3>Albums</h3>
<h4>Life of a Dark Rose</h4>
<ul>
<li></li>
<li></li>
</ul>

**Comment by arthurgrykhno** [comment]
Thanks thanks!!!!
