### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by arthurgrykhno** [arthurgrykhno/homepage#9]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ArtemonTheHuman** [comment]
<h2>Skills</h2>
<p>Creating hits, skateboarding, make people happy</p>
<h2>Likes</h2>
<p>Love wearing expensive clothes, fast driving foreign cars, counting money &#128520</p>
<p>In love with Mary Jane &#129392 &#128525</p>
<h2>Dislikes</h2>
<p>When money ends (it doesn't &#128513)</p>
